#ifndef Cursors_H
#define Cursors_H

#include <SDL2/SDL.h>

// This file is automatically generated by the build system
// Any changes to this file will be overwritten during build

extern SDL_Cursor* cursor_default;
extern SDL_Cursor* cursor_move;
extern SDL_Cursor* cursor_move_horizontal;
extern SDL_Cursor* cursor_move_vertical;
extern SDL_Cursor* cursor_clip_right;
extern SDL_Cursor* cursor_clip_left;

extern void init_cursors();

#endif
