#ifndef Cursors_H
#define Cursors_H

#include <SDL2/SDL.h>

// This file is automatically generated by ImageToC
// Do not modify!

extern SDL_Cursor* cursor_default;
extern SDL_Cursor* cursor_move;
extern SDL_Cursor* cursor_move_vertical;
extern SDL_Cursor* cursor_move_horizontal;

extern void init_cursors();

#endif