#include "icons.hpp"
#include "images.hpp"
#include <utils.hpp>

// This file is automatically generated by ImageToCpp
// during the build process.

// Any modifications to this file will be
// overwritten during building.

SDL_Texture* icon_add = nullptr;
SDL_Texture* icon_beginning = nullptr;
SDL_Texture* icon_down = nullptr;
SDL_Texture* icon_file = nullptr;
SDL_Texture* icon_folder = nullptr;
SDL_Texture* icon_font = nullptr;
SDL_Texture* icon_magnet = nullptr;
SDL_Texture* icon_no_magnet = nullptr;
SDL_Texture* icon_pause = nullptr;
SDL_Texture* icon_play = nullptr;
SDL_Texture* icon_remove = nullptr;
SDL_Texture* icon_render = nullptr;
SDL_Texture* icon_sound = nullptr;
SDL_Texture* icon_up = nullptr;
SDL_Texture* icon_up_dir = nullptr;
SDL_Texture* icon_video = nullptr;

SDL_Texture* create_texture(SDL_Renderer* renderer, void* data, int width, int height) {
    const auto surface = CreateSdlSurfaceFromPng(data);
end:
    auto tex = SDL_CreateTextureFromSurface(renderer, surface);
    SDL_FreeSurface(surface);
    return tex;
}

void init_icons(SDL_Renderer* renderer) {
    icon_add = create_texture(renderer, icon_add_data, 9830406, -251);
    icon_beginning = create_texture(renderer, icon_beginning_data, 16, 16);
    icon_down = create_texture(renderer, icon_down_data, 16, 16);
    icon_file = create_texture(renderer, icon_file_data, 16, 16);
    icon_folder = create_texture(renderer, icon_folder_data, 16, 16);
    icon_font = create_texture(renderer, icon_font_data, 112, 84);
    icon_magnet = create_texture(renderer, icon_magnet_data, 16, 16);
    icon_no_magnet = create_texture(renderer, icon_no_magnet_data, 16, 16);
    icon_pause = create_texture(renderer, icon_pause_data, 16, 16);
    icon_play = create_texture(renderer, icon_play_data, 16, 16);
    icon_remove = create_texture(renderer, icon_remove_data, 16, 16);
    icon_render = create_texture(renderer, icon_render_data, 16, 16);
    icon_sound = create_texture(renderer, icon_sound_data, 16, 16);
    icon_up = create_texture(renderer, icon_up_data, 16, 16);
    icon_up_dir = create_texture(renderer, icon_up_dir_data, 16, 16);
    icon_video = create_texture(renderer, icon_video_data, 16, 16);
}
