#ifndef Icons_H
#define Icons_H

#include <SDL2/SDL.h>

// this file is automatically generated by ImageToC
// Do not modify!

extern SDL_Texture* icon_file;
extern SDL_Texture* icon_folder;
extern SDL_Texture* icon_up_dir;
extern SDL_Texture* icon_font;

extern void init_icons(SDL_Renderer* renderer);

#endif