#ifndef Icons_H
#define Icons_H

#include <SDL2/SDL.h>

// This file is automatically generated by the build system
// Any changes to this file will be overwritten during build

extern SDL_Texture* icon_file;
extern SDL_Texture* icon_render;
extern SDL_Texture* icon_beginning;
extern SDL_Texture* icon_sound;
extern SDL_Texture* icon_folder;
extern SDL_Texture* icon_up;
extern SDL_Texture* icon_font;
extern SDL_Texture* icon_no_magnet;
extern SDL_Texture* icon_up_dir;
extern SDL_Texture* icon_edit;
extern SDL_Texture* icon_video;
extern SDL_Texture* icon_pause;
extern SDL_Texture* icon_play;
extern SDL_Texture* icon_down;
extern SDL_Texture* icon_remove;
extern SDL_Texture* icon_back;
extern SDL_Texture* icon_magnet;
extern SDL_Texture* icon_add;

extern void init_icons(SDL_Renderer* renderer);

#endif
