#pragma once

// This file is automatically generated by ImageToCpp during the build process.
// Any modifications to this file will be overwritten during building

extern unsigned char icon_add_data[];
extern unsigned char* icon_add_length;
extern unsigned char icon_cursor_clip_left_data[];
extern unsigned char* icon_cursor_clip_left_length;
extern unsigned char icon_sound_data[];
extern unsigned char* icon_sound_length;
extern unsigned char icon_render_data[];
extern unsigned char* icon_render_length;
extern unsigned char icon_up_dir_data[];
extern unsigned char* icon_up_dir_length;
extern unsigned char icon_pause_data[];
extern unsigned char* icon_pause_length;
extern unsigned char icon_video_data[];
extern unsigned char* icon_video_length;
extern unsigned char icon_no_magnet_data[];
extern unsigned char* icon_no_magnet_length;
extern unsigned char icon_magnet_data[];
extern unsigned char* icon_magnet_length;
extern unsigned char icon_remove_data[];
extern unsigned char* icon_remove_length;
extern unsigned char icon_up_data[];
extern unsigned char* icon_up_length;
extern unsigned char icon_folder_data[];
extern unsigned char* icon_folder_length;
extern unsigned char icon_beginning_data[];
extern unsigned char* icon_beginning_length;
extern unsigned char icon_font_data[];
extern unsigned char* icon_font_length;
extern unsigned char icon_cursor_clip_right_data[];
extern unsigned char* icon_cursor_clip_right_length;
extern unsigned char icon_file_data[];
extern unsigned char* icon_file_length;
extern unsigned char icon_play_data[];
extern unsigned char* icon_play_length;
extern unsigned char icon_down_data[];
extern unsigned char* icon_down_length;
